name: testing
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  shared_preferences: ^2.2.2
  animate_do: ^3.3.4
  pinput: ^4.0.0
  http: ^1.2.1
  curved_navigation_bar: ^1.0.3
  lottie: ^3.1.0
  font_awesome_flutter: ^10.7.0
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  badges: ^3.1.2
  dropdown_button2: ^2.3.9
  pdf: ^3.10.8
  open_file: ^3.3.2
  path_provider: ^2.1.3
  firebase_core: ^2.29.0
  firebase_messaging: ^14.8.1
  syncfusion_flutter_pdf: ^25.1.40

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - images/
